version: '3'
services:
  # Start a password-protected Redis instance on the default port.
  # @see https://redis.io/docs/management/security/#authentication
  redis:
    image: docker.io/redis:7.2
    command: >
      --requirepass password
    ports:
      - 6379:6379
  secure-client-hub:
    build: .
    ports:
      - 3000:3000
