import {
  faAddressBook,
  faArrowDownWideShort,
  faArrowUpRightFromSquare,
  faBabyCarriage,
  faBell,
  faBriefcase,
  faCalculator,
  faCircleChevronUp,
  faCircleChevronDown,
  faChevronRight,
  faCircleMinus,
  faCirclePlus,
  faCircleUser,
  faClockRotateLeft,
  faComments,
  faCommentDots,
  faEnvelopesBulk,
  faEnvelopeOpenText,
  faHandHoldingDollar,
  faKey,
  faLaptopFile,
  faListCheck,
  faLocationDot,
  faFileCircleExclamation,
  faFileContract,
  faFileImport,
  faFileInvoiceDollar,
  faFileSignature,
  faFolderOpen,
  faMapLocationDot,
  faMoneyBillTransfer,
  faPenToSquare,
  faPersonWalkingLuggage,
  faPhoneFlip,
  faQuestionCircle,
  faReceipt,
  faSchool,
  faStamp,
  faUserCheck,
  faClock,
  faTriangleExclamation,
  faXmark,
  faChevronUp,
} from '@fortawesome/free-solid-svg-icons'

export const icon = {
  'address-book': faAddressBook,
  'arrow-down-wide-short': faArrowDownWideShort,
  'arrow-up-right-from-square': faArrowUpRightFromSquare,
  'baby-carriage': faBabyCarriage,
  'bell': faBell,
  'bell-solid 1': faBell,
  'briefcase': faBriefcase,
  'calculator': faCalculator,
  'circle-chevron-up': faCircleChevronUp,
  'circle-chevron-down': faCircleChevronDown,
  'chevron-right': faChevronRight,
  'chevron-up': faChevronUp,
  'circle-minus': faCircleMinus,
  'circle-plus': faCirclePlus,
  'circle-user': faCircleUser,
  'clock-rotate-left': faClockRotateLeft,
  'comments': faComments,
  'comment-dots': faCommentDots,
  'envelopes-bulk': faEnvelopesBulk,
  'envelope-open-text': faEnvelopeOpenText,
  'hand-holding-dollar': faHandHoldingDollar,
  'key': faKey,
  'laptop-file': faLaptopFile,
  'list-check': faListCheck,
  'location-dot': faLocationDot,
  'file-circle-exclamation': faFileCircleExclamation,
  'file-contract': faFileContract,
  //file-exclamation doesn't work. Using file-circle-exclamation as a substitute
  'file-exclamation': faFileCircleExclamation,
  'file-import': faFileImport,
  'file-invoice-dollar': faFileInvoiceDollar,
  'file-signature': faFileSignature,
  'folder-open': faFolderOpen,
  'map-location-dot': faMapLocationDot,
  'money-bill-transfer': faMoneyBillTransfer,
  'pen-to-square': faPenToSquare,
  'person-walking-luggage': faPersonWalkingLuggage,
  'phone-flip': faPhoneFlip,
  'question-circle': faQuestionCircle,
  'receipt': faReceipt,
  'school': faSchool,
  'stamp': faStamp,
  'user-check': faUserCheck,
  'clock': faClock,
  'triangle-exclamation': faTriangleExclamation,
  'xmark': faXmark,
}
