import { solid } from '@fortawesome/fontawesome-svg-core/import.macro'

export const icon = {
  'address-book': solid('address-book'),
  'arrow-down-wide-short': solid('arrow-down-wide-short'),
  'arrow-up-right-from-square': solid('arrow-up-right-from-square'),
  'baby-carriage': solid('baby-carriage'),
  'bell': solid('bell'),
  'bell-solid 1': solid('bell'),
  'briefcase': solid('briefcase'),
  'calculator': solid('calculator'),
  'circle-minus': solid('circle-minus'),
  'circle-plus': solid('circle-plus'),
  'circle-user': solid('circle-user'),
  'clock-rotate-left': solid('clock-rotate-left'),
  'comments': solid('comments'),
  'comment-dots': solid('comment-dots'),
  'envelopes-bulk': solid('envelopes-bulk'),
  'envelope-open-text': solid('envelope-open-text'),
  'hand-holding-dollar': solid('hand-holding-dollar'),
  'key': solid('key'),
  'laptop-file': solid('laptop-file'),
  'list-check': solid('list-check'),
  'location-dot': solid('location-dot'),
  'file-circle-exclamation': solid('file-circle-exclamation'),
  'file-contract': solid('file-contract'),
  //file-exclamation doesn't work. Using file-circle-exclamation as a substitute
  'file-exclamation': solid('file-circle-exclamation'),
  'file-import': solid('file-import'),
  'file-invoice-dollar': solid('file-invoice-dollar'),
  'file-signature': solid('file-signature'),
  'folder-open': solid('folder-open'),
  'map-location-dot': solid('map-location-dot'),
  'money-bill-transfer': solid('money-bill-transfer'),
  'pen-to-square': solid('pen-to-square'),
  'person-walking-luggage': solid('person-walking-luggage'),
  'phone-flip': solid('phone-flip'),
  'question-circle': solid('question-circle'),
  'receipt': solid('receipt'),
  'school': solid('school'),
  'stamp': solid('stamp'),
  'user-check': solid('user-check'),
}
